pipeline {
    agent {
    dockerfile {
        filename 'Dockerfile'
        dir 'mailer'
        args '--rm'
    }
    }
    options {
        lock(extra: [[resource: "jenkins_pipeline_master"]])
    }

environment {
MAIL_CONFIG = credentials(smtp)
}
    stages {
        stage('build') {
            steps {
		script {
sh "echo ${MAIL_CONFIG}"
}		
            }
        }
    }
}
