pipeline {
    agent {
    dockerfile {
        filename 'Dockerfile'
        dir 'mailer'
    }
    }
    options {
        lock(extra: [[resource: "jenkins_pipeline_master"]])
    }
    environment {
        MAIL_CONFIG = credentials('smtp')
    }
    stages {
        stage('build') {
            steps {
dir('mailer') {
                script {
                    sh "mailer.sh"
                }
}
            }
        }
    }
}

