pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'mailer'
        }
    }
    parameters {
        stringParameter name: 'RECIPIENT_EMAIL'
        stringParameter name: 'ADDON_ENVIRONMENT'
    }
    environment {
        MAIL_CONFIG = credentials('smtp')
    }
    stages {
        stage('build') {
            steps {
                dir('mailer') {
                    script {
                        sh "ADDON_ENVIRONMENT ./mailer.sh ${env.MAIL_CONFIG} ${params.RECIPIENT_EMAIL}"
                    }
                }
            }
        }
    }
}


